// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	"context"

	errors "github.com/Red-Sock/trace-errors"
	"go.redsock.ru/toolbox/closer"

	"go.vervstack.ru/makosh/internal/config"
)

func (a *App) InitConfig() (err error) {
	a.Ctx, a.Stop = context.WithCancel(context.Background())
	closer.Add(func() error { a.Stop(); return nil })

	a.Cfg, err = config.Load()
	if err != nil {
		return errors.Wrap(err, "error reading config")
	}

	return nil
}
