// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"github.com/godverv/makosh/internal/store"
	"github.com/godverv/makosh/internal/store/in_memory"
	"github.com/godverv/makosh/internal/transport/makosh_be_impl"
	"github.com/godverv/makosh/pkg/docs"
)

type Custom struct {
	store store.EndpointsStorage
}

func (c *Custom) Init(a *App) error {
	c.store = in_memory.New()

	imp := makosh_be_impl.New(a.Cfg, c.store)

	a.ServerMaster.AddImplementation(imp)
	a.ServerMaster.AddHttpHandler(docs.Swagger())

	return nil
}
