// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"

	"google.golang.org/grpc"

	"go.vervstack.ru/makosh/internal/interceptors"
	"go.vervstack.ru/makosh/internal/transport/makosh_be_impl"
	"go.vervstack.ru/makosh/pkg/registry"
)

type Custom struct {
	reg *registry.Registry
}

func (c *Custom) Init(a *App) error {
	c.reg = registry.New()

	imp := makosh_be_impl.New(a.Cfg, c.reg)

	var opts []grpc.ServerOption

	if !a.Cfg.Environment.DisableSecurity {
		opts = append(opts, interceptors.GrpcAuthInterceptor(a.Cfg.Environment.AuthToken))
	}

	a.ServerMaster.AddImplementation(imp)
	a.ServerMaster.AddServerOption(opts...)


	return nil
}

func (c *Custom) Start(ctx context.Context) error {
	return nil
}

func (c *Custom) Stop() error {
	return nil
}
