// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	errors "github.com/Red-Sock/trace-errors"
	"github.com/godverv/makosh/internal/transport"
)

func (a *App) InitServers() (err error) {
	a.ServerMaster, err = transport.NewServerManager(a.Ctx, a.Cfg.Servers.MASTER.Port)
	if err != nil {
		return errors.Wrap(err, "error during \"MASTER\" server initialization, with name: MASTER")
	}

	return nil
}
