// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	"go.redsock.ru/rerrors"
	"go.vervstack.ru/makosh/internal/transport"
)

func (a *App) InitServers() (err error) {
	a.ServerMaster, err = transport.NewServerManager(a.Ctx, a.Cfg.Servers.MASTER.Port)
	if err != nil {
		return rerrors.Wrap(err, "error during \"MASTER\" server initialization, with name: MASTER")
	}

	return nil
}
