app_info:
    name: github.com/godverv/makosh
    version: v0.0.16
    startup_duration: 10s
servers:
    8080:
        /{GRPC}:
            module: pkg/makosh_be
            gateway: /api
environment:
    - name: auth_token
      type: string
      value: K/ENz2Bpd4IgA5NCj8qovFpGGBktQkUqVHvb6ASj1rCcd29gSfQYhRWIT3+IqVjJK9xEDvL9yI4FOZugrL2+dkGMvUYRKRTnul39dwkjoqmUc4q/WwPwlhJPwoadM1PVzVINdDV5ILRqVpHjDd9KYXY8mouI4vEd7ccwuNFWFVAg6np/+t95+pz1xQAQSkPH8UBic/5h8IULZFvNaeo5CHdQq46YUC4qUNWwqzHGLjYRNFjB6AY2QSRd80c+fuUz
    - name: disable_security
      type: bool
      value: true
