// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: makosh-be_api.proto

package makosh_be

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressScope int32

const (
	AddressScope_ADDRESS_SCOPE_UNSPECIFIED AddressScope = 0
	AddressScope_DOCKER                    AddressScope = 1
	AddressScope_VCN                       AddressScope = 2
)

// Enum value maps for AddressScope.
var (
	AddressScope_name = map[int32]string{
		0: "ADDRESS_SCOPE_UNSPECIFIED",
		1: "DOCKER",
		2: "VCN",
	}
	AddressScope_value = map[string]int32{
		"ADDRESS_SCOPE_UNSPECIFIED": 0,
		"DOCKER":                    1,
		"VCN":                       2,
	}
)

func (x AddressScope) Enum() *AddressScope {
	p := new(AddressScope)
	*p = x
	return p
}

func (x AddressScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressScope) Descriptor() protoreflect.EnumDescriptor {
	return file_makosh_be_api_proto_enumTypes[0].Descriptor()
}

func (AddressScope) Type() protoreflect.EnumType {
	return &file_makosh_be_api_proto_enumTypes[0]
}

func (x AddressScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressScope.Descriptor instead.
func (AddressScope) EnumDescriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Scope         AddressScope           `protobuf:"varint,2,opt,name=scope,proto3,enum=makosh_be_api.AddressScope" json:"scope,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // which exposed port/resource of the service this address reaches
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_makosh_be_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Address) GetScope() AddressScope {
	if x != nil {
		return x.Scope
	}
	return AddressScope_ADDRESS_SCOPE_UNSPECIFIED
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_makosh_be_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{1}
}

type ListEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpoints) Reset() {
	*x = ListEndpoints{}
	mi := &file_makosh_be_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpoints) ProtoMessage() {}

func (x *ListEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpoints.ProtoReflect.Descriptor instead.
func (*ListEndpoints) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{2}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_makosh_be_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Endpoint) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Endpoint) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type DeleteEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpoints) Reset() {
	*x = DeleteEndpoints{}
	mi := &file_makosh_be_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpoints) ProtoMessage() {}

func (x *DeleteEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpoints.ProtoReflect.Descriptor instead.
func (*DeleteEndpoints) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{4}
}

type UpsertEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEndpoints) Reset() {
	*x = UpsertEndpoints{}
	mi := &file_makosh_be_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpoints) ProtoMessage() {}

func (x *UpsertEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpoints.ProtoReflect.Descriptor instead.
func (*UpsertEndpoints) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{5}
}

type Version_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version_Request) Reset() {
	*x = Version_Request{}
	mi := &file_makosh_be_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Request) ProtoMessage() {}

func (x *Version_Request) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Request.ProtoReflect.Descriptor instead.
func (*Version_Request) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{1, 0}
}

type Version_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version_Response) Reset() {
	*x = Version_Response{}
	mi := &file_makosh_be_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Response) ProtoMessage() {}

func (x *Version_Response) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Response.ProtoReflect.Descriptor instead.
func (*Version_Response) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Version_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListEndpoints_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Scope         AddressScope           `protobuf:"varint,2,opt,name=scope,proto3,enum=makosh_be_api.AddressScope" json:"scope,omitempty"` // UNSPECIFIED = all scopes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpoints_Request) Reset() {
	*x = ListEndpoints_Request{}
	mi := &file_makosh_be_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpoints_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpoints_Request) ProtoMessage() {}

func (x *ListEndpoints_Request) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpoints_Request.ProtoReflect.Descriptor instead.
func (*ListEndpoints_Request) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListEndpoints_Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListEndpoints_Request) GetScope() AddressScope {
	if x != nil {
		return x.Scope
	}
	return AddressScope_ADDRESS_SCOPE_UNSPECIFIED
}

type ListEndpoints_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpoints_Response) Reset() {
	*x = ListEndpoints_Response{}
	mi := &file_makosh_be_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpoints_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpoints_Response) ProtoMessage() {}

func (x *ListEndpoints_Response) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpoints_Response.ProtoReflect.Descriptor instead.
func (*ListEndpoints_Response) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ListEndpoints_Response) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ListEndpoints_Response) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type DeleteEndpoints_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Scope         AddressScope           `protobuf:"varint,2,opt,name=scope,proto3,enum=makosh_be_api.AddressScope" json:"scope,omitempty"` // scope UNSPECIFIED removes the whole service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpoints_Request) Reset() {
	*x = DeleteEndpoints_Request{}
	mi := &file_makosh_be_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpoints_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpoints_Request) ProtoMessage() {}

func (x *DeleteEndpoints_Request) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpoints_Request.ProtoReflect.Descriptor instead.
func (*DeleteEndpoints_Request) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DeleteEndpoints_Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeleteEndpoints_Request) GetScope() AddressScope {
	if x != nil {
		return x.Scope
	}
	return AddressScope_ADDRESS_SCOPE_UNSPECIFIED
}

type DeleteEndpoints_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpoints_Response) Reset() {
	*x = DeleteEndpoints_Response{}
	mi := &file_makosh_be_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpoints_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpoints_Response) ProtoMessage() {}

func (x *DeleteEndpoints_Response) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpoints_Response.ProtoReflect.Descriptor instead.
func (*DeleteEndpoints_Response) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{4, 1}
}

type UpsertEndpoints_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEndpoints_Request) Reset() {
	*x = UpsertEndpoints_Request{}
	mi := &file_makosh_be_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpoints_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpoints_Request) ProtoMessage() {}

func (x *UpsertEndpoints_Request) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpoints_Request.ProtoReflect.Descriptor instead.
func (*UpsertEndpoints_Request) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpsertEndpoints_Request) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type UpsertEndpoints_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEndpoints_Response) Reset() {
	*x = UpsertEndpoints_Response{}
	mi := &file_makosh_be_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpoints_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpoints_Response) ProtoMessage() {}

func (x *UpsertEndpoints_Response) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpoints_Response.ProtoReflect.Descriptor instead.
func (*UpsertEndpoints_Response) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{5, 1}
}

var File_makosh_be_api_proto protoreflect.FileDescriptor

const file_makosh_be_api_proto_rawDesc = "" +
	"\n" +
	"\x13makosh-be_api.proto\x12\rmakosh_be_api\x1a\x1cgoogle/api/annotations.proto\"d\n" +
	"\aAddress\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x121\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x1b.makosh_be_api.AddressScopeR\x05scope\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\":\n" +
	"\aVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xc6\x01\n" +
	"\rListEndpoints\x1a_\n" +
	"\aRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x121\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x1b.makosh_be_api.AddressScopeR\x05scope\x1aT\n" +
	"\bResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x124\n" +
	"\taddresses\x18\x02 \x03(\v2\x16.makosh_be_api.AddressR\taddresses\"y\n" +
	"\bEndpoint\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x124\n" +
	"\taddresses\x18\x03 \x03(\v2\x16.makosh_be_api.AddressR\taddresses\"~\n" +
	"\x0fDeleteEndpoints\x1a_\n" +
	"\aRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x121\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x1b.makosh_be_api.AddressScopeR\x05scope\x1a\n" +
	"\n" +
	"\bResponse\"_\n" +
	"\x0fUpsertEndpoints\x1a@\n" +
	"\aRequest\x125\n" +
	"\tendpoints\x18\x01 \x03(\v2\x17.makosh_be_api.EndpointR\tendpoints\x1a\n" +
	"\n" +
	"\bResponse*B\n" +
	"\fAddressScope\x12\x1d\n" +
	"\x19ADDRESS_SCOPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DOCKER\x10\x01\x12\a\n" +
	"\x03VCN\x10\x022\xfb\x03\n" +
	"\vMakoshBeAPI\x12`\n" +
	"\aVersion\x12\x1e.makosh_be_api.Version.Request\x1a\x1f.makosh_be_api.Version.Response\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/version\x12\x83\x01\n" +
	"\rListEndpoints\x12$.makosh_be_api.ListEndpoints.Request\x1a%.makosh_be_api.ListEndpoints.Response\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/endpoints/{service_name}\x12}\n" +
	"\x0fUpsertEndpoints\x12&.makosh_be_api.UpsertEndpoints.Request\x1a'.makosh_be_api.UpsertEndpoints.Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/endpoints\x12\x84\x01\n" +
	"\x0fDeleteEndpoints\x12&.makosh_be_api.DeleteEndpoints.Request\x1a'.makosh_be_api.DeleteEndpoints.Response\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/endpoints/deleteB\fZ\n" +
	"/makosh_beb\x06proto3"

var (
	file_makosh_be_api_proto_rawDescOnce sync.Once
	file_makosh_be_api_proto_rawDescData []byte
)

func file_makosh_be_api_proto_rawDescGZIP() []byte {
	file_makosh_be_api_proto_rawDescOnce.Do(func() {
		file_makosh_be_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makosh_be_api_proto_rawDesc), len(file_makosh_be_api_proto_rawDesc)))
	})
	return file_makosh_be_api_proto_rawDescData
}

var file_makosh_be_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_makosh_be_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_makosh_be_api_proto_goTypes = []any{
	(AddressScope)(0),                // 0: makosh_be_api.AddressScope
	(*Address)(nil),                  // 1: makosh_be_api.Address
	(*Version)(nil),                  // 2: makosh_be_api.Version
	(*ListEndpoints)(nil),            // 3: makosh_be_api.ListEndpoints
	(*Endpoint)(nil),                 // 4: makosh_be_api.Endpoint
	(*DeleteEndpoints)(nil),          // 5: makosh_be_api.DeleteEndpoints
	(*UpsertEndpoints)(nil),          // 6: makosh_be_api.UpsertEndpoints
	(*Version_Request)(nil),          // 7: makosh_be_api.Version.Request
	(*Version_Response)(nil),         // 8: makosh_be_api.Version.Response
	(*ListEndpoints_Request)(nil),    // 9: makosh_be_api.ListEndpoints.Request
	(*ListEndpoints_Response)(nil),   // 10: makosh_be_api.ListEndpoints.Response
	(*DeleteEndpoints_Request)(nil),  // 11: makosh_be_api.DeleteEndpoints.Request
	(*DeleteEndpoints_Response)(nil), // 12: makosh_be_api.DeleteEndpoints.Response
	(*UpsertEndpoints_Request)(nil),  // 13: makosh_be_api.UpsertEndpoints.Request
	(*UpsertEndpoints_Response)(nil), // 14: makosh_be_api.UpsertEndpoints.Response
}
var file_makosh_be_api_proto_depIdxs = []int32{
	0,  // 0: makosh_be_api.Address.scope:type_name -> makosh_be_api.AddressScope
	1,  // 1: makosh_be_api.Endpoint.addresses:type_name -> makosh_be_api.Address
	0,  // 2: makosh_be_api.ListEndpoints.Request.scope:type_name -> makosh_be_api.AddressScope
	1,  // 3: makosh_be_api.ListEndpoints.Response.addresses:type_name -> makosh_be_api.Address
	0,  // 4: makosh_be_api.DeleteEndpoints.Request.scope:type_name -> makosh_be_api.AddressScope
	4,  // 5: makosh_be_api.UpsertEndpoints.Request.endpoints:type_name -> makosh_be_api.Endpoint
	7,  // 6: makosh_be_api.MakoshBeAPI.Version:input_type -> makosh_be_api.Version.Request
	9,  // 7: makosh_be_api.MakoshBeAPI.ListEndpoints:input_type -> makosh_be_api.ListEndpoints.Request
	13, // 8: makosh_be_api.MakoshBeAPI.UpsertEndpoints:input_type -> makosh_be_api.UpsertEndpoints.Request
	11, // 9: makosh_be_api.MakoshBeAPI.DeleteEndpoints:input_type -> makosh_be_api.DeleteEndpoints.Request
	8,  // 10: makosh_be_api.MakoshBeAPI.Version:output_type -> makosh_be_api.Version.Response
	10, // 11: makosh_be_api.MakoshBeAPI.ListEndpoints:output_type -> makosh_be_api.ListEndpoints.Response
	14, // 12: makosh_be_api.MakoshBeAPI.UpsertEndpoints:output_type -> makosh_be_api.UpsertEndpoints.Response
	12, // 13: makosh_be_api.MakoshBeAPI.DeleteEndpoints:output_type -> makosh_be_api.DeleteEndpoints.Response
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_makosh_be_api_proto_init() }
func file_makosh_be_api_proto_init() {
	if File_makosh_be_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makosh_be_api_proto_rawDesc), len(file_makosh_be_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makosh_be_api_proto_goTypes,
		DependencyIndexes: file_makosh_be_api_proto_depIdxs,
		EnumInfos:         file_makosh_be_api_proto_enumTypes,
		MessageInfos:      file_makosh_be_api_proto_msgTypes,
	}.Build()
	File_makosh_be_api_proto = out.File
	file_makosh_be_api_proto_goTypes = nil
	file_makosh_be_api_proto_depIdxs = nil
}
