// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: makosh-be_api.proto

package makosh_be

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_makosh_be_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{0}
}

type ListEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpoints) Reset() {
	*x = ListEndpoints{}
	mi := &file_makosh_be_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpoints) ProtoMessage() {}

func (x *ListEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpoints.ProtoReflect.Descriptor instead.
func (*ListEndpoints) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{1}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_makosh_be_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoint) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Endpoint) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type UpsertEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEndpoints) Reset() {
	*x = UpsertEndpoints{}
	mi := &file_makosh_be_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpoints) ProtoMessage() {}

func (x *UpsertEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpoints.ProtoReflect.Descriptor instead.
func (*UpsertEndpoints) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{3}
}

type Version_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version_Request) Reset() {
	*x = Version_Request{}
	mi := &file_makosh_be_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Request) ProtoMessage() {}

func (x *Version_Request) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Request.ProtoReflect.Descriptor instead.
func (*Version_Request) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{0, 0}
}

type Version_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version_Response) Reset() {
	*x = Version_Response{}
	mi := &file_makosh_be_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Response) ProtoMessage() {}

func (x *Version_Response) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Response.ProtoReflect.Descriptor instead.
func (*Version_Response) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Version_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListEndpoints_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpoints_Request) Reset() {
	*x = ListEndpoints_Request{}
	mi := &file_makosh_be_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpoints_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpoints_Request) ProtoMessage() {}

func (x *ListEndpoints_Request) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpoints_Request.ProtoReflect.Descriptor instead.
func (*ListEndpoints_Request) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListEndpoints_Request) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ListEndpoints_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpoints_Response) Reset() {
	*x = ListEndpoints_Response{}
	mi := &file_makosh_be_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpoints_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpoints_Response) ProtoMessage() {}

func (x *ListEndpoints_Response) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpoints_Response.ProtoReflect.Descriptor instead.
func (*ListEndpoints_Response) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListEndpoints_Response) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UpsertEndpoints_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEndpoints_Request) Reset() {
	*x = UpsertEndpoints_Request{}
	mi := &file_makosh_be_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpoints_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpoints_Request) ProtoMessage() {}

func (x *UpsertEndpoints_Request) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpoints_Request.ProtoReflect.Descriptor instead.
func (*UpsertEndpoints_Request) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpsertEndpoints_Request) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type UpsertEndpoints_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEndpoints_Response) Reset() {
	*x = UpsertEndpoints_Response{}
	mi := &file_makosh_be_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEndpoints_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEndpoints_Response) ProtoMessage() {}

func (x *UpsertEndpoints_Response) ProtoReflect() protoreflect.Message {
	mi := &file_makosh_be_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEndpoints_Response.ProtoReflect.Descriptor instead.
func (*UpsertEndpoints_Response) Descriptor() ([]byte, []int) {
	return file_makosh_be_api_proto_rawDescGZIP(), []int{3, 1}
}

var File_makosh_be_api_proto protoreflect.FileDescriptor

const file_makosh_be_api_proto_rawDesc = "" +
	"\n" +
	"\x13makosh-be_api.proto\x12\rmakosh_be_api\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\":\n" +
	"\aVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"]\n" +
	"\rListEndpoints\x1a,\n" +
	"\aRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"C\n" +
	"\bEndpoint\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\"_\n" +
	"\x0fUpsertEndpoints\x1a@\n" +
	"\aRequest\x125\n" +
	"\tendpoints\x18\x01 \x03(\v2\x17.makosh_be_api.EndpointR\tendpoints\x1a\n" +
	"\n" +
	"\bResponse2\xf4\x02\n" +
	"\vMakoshBeAPI\x12`\n" +
	"\aVersion\x12\x1e.makosh_be_api.Version.Request\x1a\x1f.makosh_be_api.Version.Response\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/version\x12\x83\x01\n" +
	"\rListEndpoints\x12$.makosh_be_api.ListEndpoints.Request\x1a%.makosh_be_api.ListEndpoints.Response\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/endpoints/{service_name}\x12}\n" +
	"\x0fUpsertEndpoints\x12&.makosh_be_api.UpsertEndpoints.Request\x1a'.makosh_be_api.UpsertEndpoints.Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/endpointsB\x1f\x92\x82\x19\x0f@godverv/makoshZ\n" +
	"/makosh_beb\x06proto3"

var (
	file_makosh_be_api_proto_rawDescOnce sync.Once
	file_makosh_be_api_proto_rawDescData []byte
)

func file_makosh_be_api_proto_rawDescGZIP() []byte {
	file_makosh_be_api_proto_rawDescOnce.Do(func() {
		file_makosh_be_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makosh_be_api_proto_rawDesc), len(file_makosh_be_api_proto_rawDesc)))
	})
	return file_makosh_be_api_proto_rawDescData
}

var file_makosh_be_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_makosh_be_api_proto_goTypes = []any{
	(*Version)(nil),                  // 0: makosh_be_api.Version
	(*ListEndpoints)(nil),            // 1: makosh_be_api.ListEndpoints
	(*Endpoint)(nil),                 // 2: makosh_be_api.Endpoint
	(*UpsertEndpoints)(nil),          // 3: makosh_be_api.UpsertEndpoints
	(*Version_Request)(nil),          // 4: makosh_be_api.Version.Request
	(*Version_Response)(nil),         // 5: makosh_be_api.Version.Response
	(*ListEndpoints_Request)(nil),    // 6: makosh_be_api.ListEndpoints.Request
	(*ListEndpoints_Response)(nil),   // 7: makosh_be_api.ListEndpoints.Response
	(*UpsertEndpoints_Request)(nil),  // 8: makosh_be_api.UpsertEndpoints.Request
	(*UpsertEndpoints_Response)(nil), // 9: makosh_be_api.UpsertEndpoints.Response
}
var file_makosh_be_api_proto_depIdxs = []int32{
	2, // 0: makosh_be_api.UpsertEndpoints.Request.endpoints:type_name -> makosh_be_api.Endpoint
	4, // 1: makosh_be_api.MakoshBeAPI.Version:input_type -> makosh_be_api.Version.Request
	6, // 2: makosh_be_api.MakoshBeAPI.ListEndpoints:input_type -> makosh_be_api.ListEndpoints.Request
	8, // 3: makosh_be_api.MakoshBeAPI.UpsertEndpoints:input_type -> makosh_be_api.UpsertEndpoints.Request
	5, // 4: makosh_be_api.MakoshBeAPI.Version:output_type -> makosh_be_api.Version.Response
	7, // 5: makosh_be_api.MakoshBeAPI.ListEndpoints:output_type -> makosh_be_api.ListEndpoints.Response
	9, // 6: makosh_be_api.MakoshBeAPI.UpsertEndpoints:output_type -> makosh_be_api.UpsertEndpoints.Response
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_makosh_be_api_proto_init() }
func file_makosh_be_api_proto_init() {
	if File_makosh_be_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makosh_be_api_proto_rawDesc), len(file_makosh_be_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makosh_be_api_proto_goTypes,
		DependencyIndexes: file_makosh_be_api_proto_depIdxs,
		MessageInfos:      file_makosh_be_api_proto_msgTypes,
	}.Build()
	File_makosh_be_api_proto = out.File
	file_makosh_be_api_proto_goTypes = nil
	file_makosh_be_api_proto_depIdxs = nil
}
